import type { Project } from "../types";

export const tessera: Project = {
  slug: "tessera",
  name: "Tessera",
  discipline: "Game",
  status: "In Production",
  blurb:
    "A game about reassembling shattered pottery, where every puzzle is generated by actually breaking something — and the shard-matching algorithm is the mechanic rather than the hint button.",
  progress: 20,
  year: "2026",
  cover: "/work/tessera/cover.png",
  caseStudy: {
    tagline: "The matcher is the game.",
    role: "Game design, fracture simulation, shard matching, native build",
    timeframe: "2026 — in production",
    overview: [
      "Tessera is about putting broken things back together — a bowl, a mosaic floor, a tablet in four hundred pieces. There are no authored puzzles. Every object is made whole and then genuinely broken by a fracture simulation that propagates cracks through the material from the blow, so the pieces fit for the only reason pieces ever fit: they were one piece.",
      "That's the design bet in full. The moment a jigsaw is hand-authored, its difficulty is a level designer's opinion about difficulty. When the object is really broken, the difficulty is the object's.",
    ],
    metrics: [
      { value: "0", label: "Hand-authored puzzles" },
      { value: "1 in 9", label: "Generated digs rejected as ambiguous" },
      { value: "20%", label: "Build progress" },
    ],
    sections: [
      {
        heading: "Break it properly and the puzzle comes free",
        body: [
          "A Voronoi shatter looks broken and doesn't behave broken. Every edge comes out straight, every piece convex, and ten minutes in you are matching straight lines to straight lines with nothing to go on but colour. It is the cheap version and it poisons the whole loop.",
          "So cracks are seeded at the impact and propagated along the stresses through a wall of a given thickness, curvature and material. What that buys is exactly what makes reassembly possible in a real conservation lab: a curved edge with a profile, a thickness that steps where the wall thins toward the rim, a painted line that has to continue across a join, and a fresh break that reads differently from a weathered one.",
        ],
      },
      {
        heading: "Solvable isn't the bar. Unambiguous is.",
        body: [
          "Generation guarantees a solution exists — you cannot break something into pieces that don't reassemble. It guarantees nothing about whether the solution is findable, and nothing at all about it being the only one. A rim sherd from a symmetrical bowl can sit in four places equally well, and a puzzle where the correct join is indistinguishable from three wrong ones isn't hard. It's unfair.",
          "Every generated dig is therefore run through the matcher before a player ever sees it, and any dig with joins the matcher can't separate by a clear margin is thrown away rather than shipped. About one in nine doesn't survive. That check turns out to be the difficulty dial as well: an easy dig is one whose margins are wide.",
        ],
      },
      {
        heading: "Assist is the algorithm, shown",
        body: [
          "Difficulty isn't piece count, it's how much of the matcher you're allowed to see. At the top level you get the shards and your own eyes. Below that it will group by thickness class, then show edge curvature, then confirm a join before you commit to it.",
          "It's the same instrument the generator uses to check its own work, which makes learning the game learning to see what it sees — the step in a wall, the way a curve continues, the roughness of one break against another.",
        ],
      },
      {
        heading: "Nothing here is worth anything",
        body: [
          "No timer, no lives, no energy, no daily. Nothing in Tessera has a price, trades, or falls out of a pack — the lab already has a game about a market, and this is deliberately the opposite of it.",
          "What accumulates is a museum: what you reassembled, what it turned out to be, and the parts still missing, which stay missing. A session ends when you set a piece down.",
        ],
      },
      {
        heading: "Where it is",
        body: [
          "The fracture generator and the matcher both run headless with tests, which is the part that had to be true before anything else was worth doing: if the pieces don't really fit, no amount of art rescues it. The ambiguity pass is in, and it has already caught the failure it was written for — symmetrical vessels producing four-way ties on rim sherds, which was the exact thing that would have made the game feel arbitrary and broken.",
          "What's honestly not finished: most of what you can see. Handling shards on a touch screen is prototyped and not solved. The dig fiction, the objects and their catalogue aren't written. There is no art direction beyond a grey clay material. iOS first, Android after — the simulation and the matcher are a separate engine with no platform types in them, so the second build is a port rather than a rewrite.",
        ],
      },
    ],
    stack: ["Rust", "Swift", "Metal", "iOS", "Android"],
    waitlist: {
      platforms: ["iOS", "Android"],
      blurb:
        "Tessera is heading for a beta on iOS and Android. Leave your email and we'll send you an invite and a first dig when it opens.",
    },
  },
};
